// Code generated by "stringer -type=Target"; DO NOT EDIT.

package option

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TargetField-1]
	_ = x[TargetNamed-2]
	_ = x[TargetPkg-3]
	_ = x[TargetFunc-4]
	_ = x[TargetConst-5]
	_ = x[TargetVar-6]
	_ = x[TargetMethod-7]
	_ = x[TargetIface-8]
	_ = x[TargetImport-9]
	_ = x[TargetAlias-10]
	_ = x[TargetIfaceSig-11]
	_ = x[TargetStruct-12]
	_ = x[TargetAny-13]
}

const _Target_name = "TargetFieldTargetNamedTargetPkgTargetFuncTargetConstTargetVarTargetMethodTargetIfaceTargetImportTargetAliasTargetIfaceSigTargetStructTargetAny"

var _Target_index = [...]uint8{0, 11, 22, 31, 41, 52, 61, 73, 84, 96, 107, 121, 133, 142}

func (i Target) String() string {
	i -= 1
	if i < 0 || i >= Target(len(_Target_index)-1) {
		return "Target(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Target_name[_Target_index[i]:_Target_index[i+1]]
}
