// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package marker

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STRING-1]
	_ = x[FLOAT-2]
	_ = x[INT-3]
	_ = x[COMPLEX-4]
	_ = x[BOOL-5]
	_ = x[LIST-6]
}

const _Kind_name = "STRINGFLOATINTCOMPLEXBOOLLIST"

var _Kind_index = [...]uint8{0, 6, 11, 14, 21, 25, 29}

func (i Kind) String() string {
	i -= 1
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
