// Code generated by "stringer -type=MarkerKind"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MarkerKindString-1]
	_ = x[MarkerKindFloat-2]
	_ = x[MarkerKindInt-3]
	_ = x[MarkerKindComplex-4]
	_ = x[MarkerKindBool-5]
	_ = x[MarkerKindList-6]
}

const _MarkerKind_name = "MarkerKindStringMarkerKindFloatMarkerKindIntMarkerKindComplexMarkerKindBoolMarkerKindList"

var _MarkerKind_index = [...]uint8{0, 16, 31, 44, 61, 75, 89}

func (i MarkerKind) String() string {
	i -= 1
	if i < 0 || i >= MarkerKind(len(_MarkerKind_index)-1) {
		return "MarkerKind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MarkerKind_name[_MarkerKind_index[i]:_MarkerKind_index[i+1]]
}
