// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-1]
	_ = x[ERROR-2]
	_ = x[STRING-3]
	_ = x[BOOL-4]
	_ = x[IDENT-5]
	_ = x[ASSIGN-6]
	_ = x[PLUS-7]
	_ = x[LBRACK-8]
	_ = x[RBRACK-9]
	_ = x[INT-10]
	_ = x[FLOAT-11]
	_ = x[COMPLEX-12]
	_ = x[COMMA-13]
}

const _Kind_name = "EOFERRORSTRINGBOOLIDENTASSIGNPLUSLBRACKRBRACKINTFLOATCOMPLEXCOMMA"

var _Kind_index = [...]uint8{0, 3, 8, 14, 18, 23, 29, 33, 39, 45, 48, 53, 60, 65}

func (i Kind) String() string {
	i -= 1
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
