// Code generated by "stringer -type=Target"; DO NOT EDIT.

package sdk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TargetField-1]
	_ = x[TargetType-2]
	_ = x[TargetPackage-3]
	_ = x[TargetFunc-4]
	_ = x[TargetConst-5]
	_ = x[TargetVar-6]
	_ = x[TargetMethod-7]
	_ = x[TargetInterface-8]
	_ = x[TargetImport-9]
	_ = x[TargetAlias-10]
	_ = x[TargetInterfaceSignature-11]
	_ = x[TargetStruct-12]
	_ = x[TargetAny-13]
}

const _Target_name = "TargetFieldTargetTypeTargetPackageTargetFuncTargetConstTargetVarTargetMethodTargetInterfaceTargetImportTargetAliasTargetInterfaceSignatureTargetStructTargetAny"

var _Target_index = [...]uint8{0, 11, 21, 34, 44, 55, 64, 76, 91, 103, 114, 138, 150, 159}

func (i Target) String() string {
	i -= 1
	if i < 0 || i >= Target(len(_Target_index)-1) {
		return "Target(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Target_name[_Target_index[i]:_Target_index[i+1]]
}
